Repository 2024-line4-earth/New_Joinus_FE, pull requests merged in 2025-03, with the labels that each got.

#4 [🎨 Design]/#3 푸터 UI 구현 완료
  src/assets/icons/Join.svg
  src/assets/icons/Rank.svg
  src/assets/icons/Share.svg
  src/assets/icons/Us.svg
  src/assets/icons/react.svg
  src/assets/image/mainLogo.png
  src/components/common/CommonFooter.styled.ts
  src/components/common/CommonFooter.tsx
  src/pages/joinPage/JoinMain.tsx
  src/router.tsx
Labels: 🎨 Design, 🦁 수용

#6 🎨[ Design] / #3 : 푸터 UI 구현 완료
  src/assets/icons/Join.svg
  src/assets/icons/Rank.svg
  src/assets/icons/Share.svg
  src/assets/icons/Us.svg
  src/assets/icons/react.svg
  src/assets/image/mainLogo.png
  src/components/common/CommonFooter.styled.ts
  src/components/common/CommonFooter.tsx
  src/pages/joinPage/JoinMain.tsx
  src/router.tsx
Labels: 🎨 Design, 🦁 수용

#10 [🎨 Design]/#7 Join 메인 페이지 UI 구현 완료
  src/assets/icons/ImgBox.svg
  src/components/common/CommonFooter.styled.ts
  src/layout/FooterLayout.tsx
  src/pages/joinPage/JoinMain.styled.ts
  src/pages/joinPage/JoinMain.tsx
  src/router.tsx
Labels: 🎨 Design, 🦁 수용

#11 :lipstick: Design: US 페이지 UI 구현 완료
  src/assets/img/us/card.svg
  src/assets/img/us/market/frame1.svg
  src/assets/img/us/market/frame2.svg
  src/assets/img/us/market/marketImg.svg
  src/assets/img/us/market/sticker.svg
  src/assets/img/us/market/theme.svg
  src/assets/img/us/menu.svg
  src/assets/img/us/step0.svg
  src/assets/img/us/step1.svg
  src/assets/img/us/step1Pink.svg
  src/assets/img/us/step2.svg
  src/assets/img/us/step2Pink.svg
  src/assets/img/us/step3.svg
  src/assets/img/us/step3Pink.svg
  src/assets/img/us/step4.svg
  src/assets/img/us/step4Pink.svg
  src/assets/img/us/stepImg.svg
  src/components/us/UsMain.tsx
  src/components/us/UsMarket.tsx
  src/components/us/UsRanking.tsx
  src/components/us/UsStepCard.tsx
  src/components/us/menu/UsMenu.tsx
  src/components/us/menu/styled.ts
  src/components/us/styled.ts
  src/pages/UsPage.tsx
  src/router.tsx
Labels: 🎨 Design, 🦁 동은

#14 Design: US 페이지 menu UI 구현
  src/assets/img/us/menu/back.svg
  src/assets/img/us/menu/edit.svg
  src/assets/img/us/menu/logout.svg
  src/assets/img/us/menu/quit.svg
  src/assets/img/us/menu/send.svg
  src/assets/img/us/menu/shopping.svg
  src/assets/img/us/menu/theme.svg
  src/components/us/menu/UsMenu.tsx
  src/components/us/menu/styled.ts
  src/pages/UsPage.tsx
Labels: 🎨 Design, 🦁 동은

#15 🔧 [Chore] - 코드에디터 상에서 @적용 안되는 문제를 해결했습니다.
  src/assets/image/card.png
  src/components/common/CommonFooter.styled.ts
  src/components/common/CommonFooter.tsx
  src/components/ranking/RankUser.tsx
  src/components/ranking/Rankin.style.ts
  src/layout/FooterLayout.tsx
  src/pages/RankPage.tsx
  src/router.tsx
  tsconfig.app.json
Labels: 🧑‍🔧 Fix, 🦁 성재
