Repository 2024-line4-earth/New_Joinus_FE, pull requests merged in 2025-06, with the labels that each got.

#50 Feat: 스켈레톤 로딩 / Fix: 인터셉터로 토큰을 항상 동적으로 불러오기
  package-lock.json
  package.json
  src/api/ApiWithToken.ts
  src/api/us/UsApi.tsx
  src/components/us/UsStepCard.tsx
Labels: 🧑‍🔧 Fix, 🦁 동은

#51 Revert "Feat: 스켈레톤 로딩 / Fix: 인터셉터로 토큰을 항상 동적으로 불러오기"
  package-lock.json
  package.json
  src/api/ApiWithToken.ts
  src/api/us/UsApi.tsx
  src/components/us/UsStepCard.tsx
Labels: 🧑‍🔧 Fix, 🦁 동은

#52 Feat: 스켈레톤 로딩 / Fix: 인터셉터로 토큰을 항상 동적으로 불러오기
  package-lock.json
  package.json
  src/api/ApiWithToken.ts
  src/api/us/UsApi.tsx
  src/components/us/UsStepCard.tsx
Labels: 🧑‍🔧 Fix, 🦁 동은

#47 [Feat]/#41 조인 페이지 네비게이션 설정
  .gitignore
  package-lock.json
  package.json
  src/components/common/common.style.tsx
  src/pages/joinPage/JoinCate.tsx
  src/pages/joinPage/JoinMain.tsx
  src/pages/joinPage/JoinStart.tsx
  src/pages/joinPage/JoinUpload.styled.ts
  src/pages/joinPage/JoinUpload.tsx
  vite.config.ts
Labels: ✨ Feature, 🦁 수용

#61 [feat]/#57 조인 페이지 api 연결 완료
  src/components/join/JoinComplete.tsx
  src/pages/joinPage/JoinCate.styled.ts
  src/pages/joinPage/JoinCate.tsx
  src/pages/joinPage/JoinFrame.styled.ts
  src/pages/joinPage/JoinFrame.tsx
  src/pages/joinPage/JoinMain.tsx
  src/pages/joinPage/JoinPost.tsx
  src/pages/joinPage/JoinPostDetail.styled.ts
  src/pages/joinPage/JoinPostDetail.tsx
  src/pages/joinPage/JoinStart.tsx
  src/pages/joinPage/JoinUpload.tsx
  src/router.tsx
Labels: 🔗 API, 🦁 수용

#67 [Fix]/#62 - 조인 페이지 기능 오류 최종 수정 완료
  src/components/common/CommonFooter.styled.ts
  src/components/common/CommonFooter.tsx
  src/components/join/JoinComplete.styled.ts
  src/components/join/JoinComplete.tsx
  src/pages/joinPage/JoinCate.tsx
  src/pages/joinPage/JoinFrame.styled.ts
  src/pages/joinPage/JoinFrame.tsx
  src/pages/joinPage/JoinMain.styled.ts
  src/pages/joinPage/JoinMain.tsx
  src/pages/joinPage/JoinPost.styled.ts
  src/pages/joinPage/JoinPost.tsx
  src/pages/joinPage/JoinPostDetail.tsx
  src/pages/joinPage/JoinUpload.tsx
  src/router.tsx
Labels: 🎨 Design, 🧑‍🔧 Fix, 🦁 수용

#70 [Fix]/#62 : 이미지 저장 비율 수정
  src/components/join/JoinComplete.tsx
  src/pages/joinPage/JoinFrame.tsx
Labels: 🧑‍🔧 Fix, 🦁 수용
